apiVersion: vjailbreak.k8s.stellaris-migrate.io/v1alpha1
kind: NetworkMapping
metadata:
  name: networkmapping
  namespace: migration-system
spec:
  networks:
    - source: VM Network
      target: vlan1
    - source: VM Network 2
      target: vlan2
