apiVersion: apps/v1
kind: Deployment
metadata:
  name: stellaris-migrate-ui
  namespace: migration-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stellaris-migrate-ui
  template:
    metadata:
      labels:
        app: stellaris-migrate-ui
    spec:
      serviceAccountName: migration-controller-manager
      containers:
        - name: stellaris-migrate-ui-container
          image: quay.io/stellaris/stellaris-migrate-ui:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stellaris-migrate-ui-service
  namespace: migration-system
spec:
  selector:
    app: stellaris-migrate-ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stellaris-migrate-ui-ingress
  namespace: migration-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stellaris-migrate-ui-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stellaris-migrate-api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /(apis.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes
            port:
              number: 443
      - path: /(api.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes
            port:
              number: 443