# permissions for end users to view clustermigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: clustermigration-viewer-role
rules:
- apiGroups:
  - migrate.k8s.stellaris.io
  resources:
  - clustermigrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migrate.k8s.stellaris.io
  resources:
  - clustermigrations/status
  verbs:
  - get
