# permissions for end users to edit migrationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: migrationtemplate-editor-role
rules:
- apiGroups:
  - vjailbreak.k8s.stellaris-migrate.io
  resources:
  - migrationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vjailbreak.k8s.stellaris-migrate.io
  resources:
  - migrationtemplates/status
  verbs:
  - get
