# permissions for end users to view networkmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: networkmapping-viewer-role
rules:
- apiGroups:
  - migrate.k8s.stellaris.io
  resources:
  - networkmappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migrate.k8s.stellaris.io
  resources:
  - networkmappings/status
  verbs:
  - get
