# permissions for end users to view pcdclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: pcdcluster-viewer-role
rules:
- apiGroups:
  - migrate.k8s.stellaris.io
  resources:
  - pcdclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migrate.k8s.stellaris.io
  resources:
  - pcdclusters/status
  verbs:
  - get
