# permissions for end users to view storagemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: storagemapping-viewer-role
rules:
- apiGroups:
  - migrate.k8s.stellaris.io
  resources:
  - storagemappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migrate.k8s.stellaris.io
  resources:
  - storagemappings/status
  verbs:
  - get
